networks:
  ssu_network:

services:
  app-service:
    build:
      context: .
      dockerfile: ./php/dockerfile
    container_name: ssu_app_container
    # command: ["sh", "-c", "tail -f /dev/null"]
    # restart: unless-stopped
    volumes:
      - ./ssu_app:/var/www/html/ssu_app
    ports:
      - "9000:9000"
    networks:
      - ssu_network
  
  nginx-service:
    image: nginx:stable-alpine
    container_name: ssu_nginx_container
    # command: ["sh", "-c", "tail -f /dev/null"]
    ports:
      - "8080:80"
    volumes:
      - ./ssu_app:/var/www/html/ssu_app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-service
    networks:
      - ssu_network

